#cloud-config
write_files:
- encoding: b64
  content: "{0}"
  owner: root:root
  path: /usr/lib/systemd/system/jupyter.service
  permissions: '0640'

runcmd:
- while [ $(systemctl status docker | grep "active (running)" | wc -l) -lt 1 ]; do sleep 5; done
- sleep 60
- systemctl enable jupyter.service
- systemctl start jupyter.service