services:
  ai-unlimited:
    deploy:
      replicas: 1
    platform: linux/amd64
    container_name: ai-unlimited-workspaces
    image: ${AI_UNLIMITED_IMAGE_NAME:-teradata/ai-unlimited-workspaces}:${AI_UNLIMITED_IMAGE_TAG:-v0.3.0}
    command: workspaces serve -v
    restart: unless-stopped
    ports:
      - "${TD_VCD_AUTH_PORT:-3000}:${TD_VCD_AUTH_PORT:-3000}/tcp"
      - "${TD_VCD_API_PORT:-3282}:${TD_VCD_API_PORT:-3282}/tcp"
    environment:
      accept_license: "Y"
      TZ: ${AI_UNLIMITED_TZ:-UTC}
      TD_VCD_API_PORT: "${TD_VCD_API_PORT:-3282}"
      TD_VCD_AUTH_PORT: "${TD_VCD_AUTH_PORT:-3000}"
      TD_VCD_INIT_API_KEY: "${AI_UNLIMITED_INIT_API_KEY:?Initial API key is required, please run the generate api key script.}"
      TD_VCD_LOG_LEVEL: "${AI_UNLIMITED_LOG_LEVEL:-INFO}"
    volumes:
      - ssl_certs:/etc/td/ssl
      - ${AI_UNLIMITED_HOME:-./volumes/ai-unlimited-workspaces}:/etc/td
    networks:
      - ai-unlimited-network

  ai-unlimited-ui:
    deploy:
      replicas: 1
    platform: linux/amd64
    container_name: ai-unlimited-workspaces-ui
    image: ${AI_UNLIMITED_UI_IMAGE_NAME:-teradata/ai-unlimited-workspaces-ui}:${AI_UNLIMITED_UI_IMAGE_TAG:-v0.1.0}
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    environment:
      TD_VCD_USE_TLS: "${TD_VCD_USE_TLS:-false}"
      TD_VCD_API_PORT: "${TD_VCD_API_PORT:-3282}"
      TD_VCD_AUTH_PORT: "${TD_VCD_AUTH_PORT:-3000}"
      TD_VCD_INIT_API_KEY: "${AI_UNLIMITED_INIT_API_KEY:?Initial API key is required, please run the generate api key script.}"
    volumes:
      - ssl_certs:/etc/ssl/td
    networks:
      - ai-unlimited-network

volumes:
  ssl_certs:
    # external: true

# make the volume external if you'd like to preload the certificate & private key in advance. Like so:
# docker volume create ssl_certs
# docker run --rm -v ${PWD}/ssl:/source -v ssl_certs:/dest busybox cp -r /source/certs /source/private /dest/

networks:
  ai-unlimited-network:
    name: ai-unlimited-network
