version: "3.9"

services:
  ai-unlimited:
    deploy:
      replicas: 1
    platform: linux/amd64
    container_name: ai-unlimited-workspaces
    image: ${WORKSPACES_IMAGE_NAME:-docker.io/teradata/regulus-workspaces}:latest
    command: workspaces serve -v
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "3000:3000/tcp"
      - "3282:3282/tcp"
    environment:
      accept_license: "Y"
      TZ: ${AI_UNLIMITED_TZ:-UTC}
      TD_VCD_INIT_API_KEY: "${AI_UNLIMITED_INIT_API_KEY:?Initial API key is required, please run the generate api key script.}"
    volumes:
      - ${AI_UNLIMITED_HOME:-./volumes/ai-unlimited-workspaces}:/etc/td
    networks:
      - ai-unlimited
  ai-unlimited-front-end:
    deploy:
      replicas: 1
    platform: linux/amd64
    container_name: workspaces-ui
    image: ${WORKSPACES_UI_IMAGE_NAME:-teradata/regulus-workspaces-ui}:${WORKSPACES_UI_IMAGE_TAG:-latest}
    ports:
      - "${TD_VCD_UI_PORT:-80}:80/tcp"
    environment:
      TD_VCD_UI_BASE_URL: "http://localhost"
      TD_VCD_UI_PORT: "${TD_VCD_UI_PORT:-80}"
      TD_VCD_API_BASE_URL: "http://localhost"
      TD_VCD_API_PORT: "${TD_VCD_API_PORT:-3282}"
      TD_VCD_AUTH_PORT: "${TD_VCD_AUTH_PORT:-3000}"
      TD_VCD_INIT_API_KEY: "${AI_UNLIMITED_INIT_API_KEY:?Initial API key is required, please run the generate api key script.}"
    networks:
      - ai-unlimited-network
networks:
  ai-unlimited-network:
    name: ai-unlimited-network